baseURL = "https://huwenbiao.github.io/"
languageCode = "zh-cn"
title = "Wenbiao's Home"
theme = "PaperMod"
hasCJKLanguage = "true"

[[menu.main]]
  name = "ä¸»é¡µ"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "åšå®¢"
  weight = 2
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "æ ‡ç­¾"
  weight = 3
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "å­˜æ¡£"
  weight = 4
  identifier = "archives"
  url = "/archives/"

[[menu.main]]
  name = "æœç´¢ ğŸ”ï¸"
  weight = 5
  identifier = "search"
  url = "/search/"

[params.profileMode]
enabled = true
title = "å°é™¢å„¿"
subtitle = "æˆ‘æœ‰ä¸€æ‰€å°é™¢å„¿ï¼Œé—¨å‰çœ‹ä¹¦ï¼Œé™¢åç§èœå„¿"
imageUrl = "home.png"
imageTitle = "å°ä¹¦åº—"
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "email"
url = "mailto:huwenbiao1989@gmail.com"
[[params.socialIcons]]
name = "github"
url = "https://github.com/huwenbiao"

# for search
[outputs]
home = [ "HTML", "RSS", "JSON" ]
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[params]
ShowCodeCopyButtons = true
ShowReadingTime = true
comments = true

[services]
  [services.googleAnalytics]
    ID = 'G-HBD4210GLV'